name: .NET
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:
    runs-on: windows-latest

    steps:
     
    - name: Environment setup
      run: echo "DLL_OUTPUT_PATH=$HOME/Outputs/" >> $GITHUB_ENV
     
   
    - name: Path echo
      run: echo "$DLL_OUTPUT_PATH"
              
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore --output ${{env.DLL_OUTPUT_PATH}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TinYard DLL
        path: ${{env.DLL_OUTPUT_PATH}}/
        
      

